site_name: Music Writer
nav:
  - Home: index.md
  - Quick Start: quickstart.md
theme:
  name: 'material'
  favicon: 'assets/images/favicon.ico'
  logo: 'assets/images/soundwave_ccf.jpg'
  palette:
    primary: 'grey'
    accent: 'blue'
